# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'web' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for web 

  pod 'SideMenu'

  target 'webTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'webUITests' do
    # Pods for testing
  end

end
